using Newtonsoft.Json;
using System.Collections.Generic;

namespace BitMagic.Compiler
{
    internal class CompileState
    {
        [JsonProperty]
        public Dictionary<string, Segment> Segments { get; set; } = new Dictionary<string, Segment>();

        [JsonProperty]
        internal Segment Segment { get; set; }
        [JsonProperty]
        internal Scope Scope { get; set; }
        [JsonProperty]
        internal Procedure Procedure { get; set; }
        [JsonProperty]
        internal Variables Globals { get; }
        [JsonProperty]
        internal int AnonCounter { get; set; }
        [JsonProperty]
        public List<string> Files { get; set; } = new List<string>();

        [JsonProperty]
        internal ScopeFactory ScopeFactory { get; set; }

        public CompileState(Variables globals)
        {
            Globals = globals;
            ScopeFactory = new ScopeFactory(Globals);

            var segment = new Segment(Globals, true, 0x801, ".DefaultSegment"); // use '.' so this cant be generated by the user
            var scope = ScopeFactory.GetScope($".DefaultScope");
            var procedure = segment.GetProcedure($".Default_{AnonCounter++}", scope, true);

            Segments.Add(segment.Name, segment);
            Segment = segment;
            Scope = scope;
            Procedure = procedure;
        }
    }
}
